services:
  postgres:
    image: postgres:16-alpine
    container_name: kroncl-db
    environment:
      POSTGRES_DB: kroncl
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - kroncl-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: kroncl-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - kroncl-network
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kroncl-api
    ports:
      - "8080:8080"
    environment:
      HOST: 0.0.0.0
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: kroncl
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_SSLMODE: disable
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ACCESS_DURATION: 1h
      JWT_REFRESH_DURATION: 7d
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - kroncl-network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  kroncl-network:
    driver: bridge