version: '3'

vars:
  MIGRATE_CMD: go run cmd/migrate/main.go

tasks:
  # Основные команды
  up:
    desc: "Применить миграции"
    cmds: ["{{.MIGRATE_CMD}} -cmd up"]
  
  down:
    desc: "Откатить миграции"
    cmds: ["{{.MIGRATE_CMD}} -cmd down"]
  
  version:
    desc: "Показать версию"
    cmds: ["{{.MIGRATE_CMD}} -cmd version"]
  
  reset:
    desc: "Сбросить базу"
    cmds:
      - "{{.MIGRATE_CMD}} -cmd down"
      - "{{.MIGRATE_CMD}} -cmd up"
  
  # СОЗДАНИЕ МИГРАЦИЙ - ПРОСТОЙ ВАРИАНТ
  migrate:create:
    desc: "Создать миграцию: task migrate:create -- init_accounts"
    cmds:
      - "{{.MIGRATE_CMD}} -cmd create -name {{.CLI_ARGS}}"
  
  # Алиасы
  "migrate:up": 
    cmds: ["{{.MIGRATE_CMD}} -cmd up"]
  
  "migrate:down":
    cmds: ["{{.MIGRATE_CMD}} -cmd down"]
  
  "migrate:version":
    cmds: ["{{.MIGRATE_CMD}} -cmd version"]