package config

const (
	PERMISSION_COMPANY_UPDATE                    = "company.update"
	PERMISSION_STORAGE_SOURCES                   = "storage.sources"
	PERMISSION_ACCOUNTS                          = "accounts"
	PERMISSION_ACCOUNTS_DELETE                   = "accounts.delete"
	PERMISSION_ACCOUNTS_INVITATIONS              = "accounts.invitations"
	PERMISSION_ACCOUNTS_INVITATIONS_CREATE       = "accounts.invitations.create"
	PERMISSION_ACCOUNTS_INVITATIONS_REVOKE       = "accounts.invitations.revoke"
	PERMISSION_HRM                               = "hrm"
	PERMISSION_HRM_EMPLOYEES                     = "hrm.employees"
	PERMISSION_HRM_EMPLOYEES_CREATE              = "hrm.employees.create"
	PERMISSION_HRM_EMPLOYEES_UPDATE              = "hrm.employees.update"
	PERMISSION_FM                                = "fm"
	PERMISSION_FM_TRANSACTIONS                   = "fm.transactions"
	PERMISSION_FM_TRANSACTIONS_CREATE            = "fm.transactions.create"
	PERMISSION_FM_TRANSACTIONS_REVERSE           = "fm.transactions.reverse"
	PERMISSION_FM_TRANSACTIONS_CATEGORIES        = "fm.transactions.categories"
	PERMISSION_FM_TRANSACTIONS_CATEGORIES_CREATE = "fm.transactions.categories.create"
	PERMISSION_FM_TRANSACTIONS_CATEGORIES_UPDATE = "fm.transactions.categories.update"
	PERMISSION_FM_TRANSACTIONS_CATEGORIES_DELETE = "fm.transactions.categories.delete"
	PERMISSION_FM_ANALYSIS                       = "fm.analysis"
	PERMISSION_FM_COUNTERPARTIES                 = "fm.counterparties"
	PERMISSION_FM_COUNTERPARTIES_CREATE          = "fm.counterparties.create"
	PERMISSION_FM_COUNTERPARTIES_UPDATE          = "fm.counterparties.update"
	PERMISSION_FM_CREDITS                        = "fm.credits"
	PERMISSION_FM_CREDITS_CREATE                 = "fm.credits.create"
	PERMISSION_FM_CREDITS_UPDATE                 = "fm.credits.update"
	PERMISSION_FM_CREDITS_PAY                    = "fm.credits.pay"
)
