package config

const PRICING_TRIAL_PERIOD_DAYS = 30
const PRICING_PLAN_LVL_1 = "stoic" // самый пиздатый
const PRICING_PLAN_LVL_2 = "titan"
const PRICING_PLAN_LVL_3 = "financier" // самый нищий
const PRICING_PLAN_MAX_LVL = 3         // самый нищий
const PRICING_PLAN_MID_LVL = 2
const PRICING_PLAN_MIN_LVL = 1 // самый пиздатый

// PermissionLvlLevel defines required tariff level for each permission
var PermissionLvl = map[string]int{
	// ========== COMPANY ==========
	PERMISSION_COMPANY_UPDATE:         PRICING_PLAN_MAX_LVL,
	PERMISSION_PRICING_MIGRATE:        PRICING_PLAN_MAX_LVL,
	PERMISSION_PRICING_TRANSACTIONS:   PRICING_PLAN_MAX_LVL,
	PERMISSION_SUPPORT_TICKETS:        PRICING_PLAN_MAX_LVL,
	PERMISSION_SUPPORT_TICKETS_CREATE: PRICING_PLAN_MAX_LVL,
	PERMISSION_SUPPORT_TICKETS_UPDATE: PRICING_PLAN_MAX_LVL,

	// ========== STORAGE ==========
	PERMISSION_STORAGE_SOURCES: PRICING_PLAN_MAX_LVL,

	// ========== ACCOUNTS ==========
	PERMISSION_ACCOUNTS:                    PRICING_PLAN_MAX_LVL,
	PERMISSION_ACCOUNTS_DELETE:             PRICING_PLAN_MAX_LVL,
	PERMISSION_ACCOUNTS_INVITATIONS:        PRICING_PLAN_MAX_LVL,
	PERMISSION_ACCOUNTS_INVITATIONS_CREATE: PRICING_PLAN_MAX_LVL,
	PERMISSION_ACCOUNTS_INVITATIONS_REVOKE: PRICING_PLAN_MAX_LVL,

	// ========== HRM ==========
	PERMISSION_HRM:                  PRICING_PLAN_MAX_LVL,
	PERMISSION_HRM_EMPLOYEES:        PRICING_PLAN_MAX_LVL,
	PERMISSION_HRM_EMPLOYEES_CREATE: PRICING_PLAN_MAX_LVL,
	PERMISSION_HRM_EMPLOYEES_UPDATE: PRICING_PLAN_MAX_LVL,

	// ========== FM ==========
	PERMISSION_FM:                                PRICING_PLAN_MAX_LVL,
	PERMISSION_FM_TRANSACTIONS:                   PRICING_PLAN_MAX_LVL,
	PERMISSION_FM_TRANSACTIONS_CREATE:            PRICING_PLAN_MAX_LVL,
	PERMISSION_FM_TRANSACTIONS_REVERSE:           PRICING_PLAN_MAX_LVL,
	PERMISSION_FM_TRANSACTIONS_CATEGORIES:        PRICING_PLAN_MAX_LVL,
	PERMISSION_FM_TRANSACTIONS_CATEGORIES_CREATE: PRICING_PLAN_MAX_LVL,
	PERMISSION_FM_TRANSACTIONS_CATEGORIES_UPDATE: PRICING_PLAN_MAX_LVL,
	PERMISSION_FM_TRANSACTIONS_CATEGORIES_DELETE: PRICING_PLAN_MAX_LVL,
	PERMISSION_FM_ANALYSIS:                       PRICING_PLAN_MAX_LVL,
	PERMISSION_FM_COUNTERPARTIES:                 PRICING_PLAN_MAX_LVL,
	PERMISSION_FM_COUNTERPARTIES_CREATE:          PRICING_PLAN_MAX_LVL,
	PERMISSION_FM_COUNTERPARTIES_UPDATE:          PRICING_PLAN_MAX_LVL,
	PERMISSION_FM_CREDITS:                        PRICING_PLAN_MAX_LVL,
	PERMISSION_FM_CREDITS_CREATE:                 PRICING_PLAN_MAX_LVL,
	PERMISSION_FM_CREDITS_UPDATE:                 PRICING_PLAN_MAX_LVL,
	PERMISSION_FM_CREDITS_TRANSACTIONS:           PRICING_PLAN_MAX_LVL,
	PERMISSION_FM_CREDITS_PAY:                    PRICING_PLAN_MAX_LVL,

	// ========== CRM ==========
	PERMISSION_CRM:                PRICING_PLAN_MID_LVL,
	PERMISSION_CRM_CLIENTS:        PRICING_PLAN_MID_LVL,
	PERMISSION_CRM_CLIENTS_CREATE: PRICING_PLAN_MID_LVL,
	PERMISSION_CRM_CLIENTS_UPDATE: PRICING_PLAN_MID_LVL,
	PERMISSION_CRM_SOURCES:        PRICING_PLAN_MID_LVL,
	PERMISSION_CRM_SOURCES_CREATE: PRICING_PLAN_MID_LVL,
	PERMISSION_CRM_SOURCES_UPDATE: PRICING_PLAN_MID_LVL,
	PERMISSION_CRM_ANALYSIS:       PRICING_PLAN_MID_LVL,

	// ========== WM ==========
	PERMISSION_WM:                           PRICING_PLAN_MID_LVL,
	PERMISSION_WM_CATALOG:                   PRICING_PLAN_MID_LVL,
	PERMISSION_WM_CATALOG_CATEGORIES:        PRICING_PLAN_MID_LVL,
	PERMISSION_WM_CATALOG_CATEGORIES_CREATE: PRICING_PLAN_MID_LVL,
	PERMISSION_WM_CATALOG_CATEGORIES_UPDATE: PRICING_PLAN_MID_LVL,
	PERMISSION_WM_CATALOG_UNITS:             PRICING_PLAN_MID_LVL,
	PERMISSION_WM_CATALOG_UNITS_CREATE:      PRICING_PLAN_MID_LVL,
	PERMISSION_WM_CATALOG_UNITS_UPDATE:      PRICING_PLAN_MID_LVL,
	PERMISSION_WM_STOCKS:                    PRICING_PLAN_MID_LVL,
	PERMISSION_WM_STOCKS_BATCHES:            PRICING_PLAN_MID_LVL,
	PERMISSION_WM_STOCKS_BATCHES_CREATE:     PRICING_PLAN_MID_LVL,
	PERMISSION_WM_STOCKS_POSITIONS:          PRICING_PLAN_MID_LVL,

	// ========== DM ==========
	PERMISSION_DM:                 PRICING_PLAN_MIN_LVL,
	PERMISSION_DM_TYPES:           PRICING_PLAN_MIN_LVL,
	PERMISSION_DM_TYPES_CREATE:    PRICING_PLAN_MIN_LVL,
	PERMISSION_DM_TYPES_UPDATE:    PRICING_PLAN_MIN_LVL,
	PERMISSION_DM_TYPES_DELETE:    PRICING_PLAN_MIN_LVL,
	PERMISSION_DM_STATUSES:        PRICING_PLAN_MIN_LVL,
	PERMISSION_DM_STATUSES_CREATE: PRICING_PLAN_MIN_LVL,
	PERMISSION_DM_STATUSES_UPDATE: PRICING_PLAN_MIN_LVL,
	PERMISSION_DM_STATUSES_DELETE: PRICING_PLAN_MIN_LVL,
	PERMISSION_DM_DEALS:           PRICING_PLAN_MIN_LVL,
	PERMISSION_DM_DEALS_CREATE:    PRICING_PLAN_MIN_LVL,
	PERMISSION_DM_DEALS_UPDATE:    PRICING_PLAN_MIN_LVL,
	PERMISSION_DM_DEALS_DELETE:    PRICING_PLAN_MIN_LVL,
	PERMISSION_DM_ANALYSIS:        PRICING_PLAN_MIN_LVL,
}

// GetPermissionLvl returns required tariff level for a permission
// Returns PRICING_PLAN_MIN_LVL if permission not found
func GetPermissionLvl(permission string) int {
	if lvl, ok := PermissionLvl[permission]; ok {
		return lvl
	}
	return PRICING_PLAN_MAX_LVL
}
