package config

const (
	RATE_LIMIT_PUBLIC_ROUTES_PER_MINUTE   = 20
	RATE_LIMIT_PRIVATE_ROUTES_PER_MINUTE  = 2000
	RATE_LIMIT_FILES_GENERATED_PER_MINUTE = 5
	RATE_LIMIT_DADATA_ROUTES_PER_MINUTE   = 50
)
