package config

const (
	WORKER_METRICS_DB_PERIOD_CRON        = "@every 60s"
	WORKER_METRICS_CLIENTELE_PERIOD_CRON = "@every 60s"
	WORKER_METRICS_SERVER_PERIOD_CRON    = "@every 60s"
	WORKER_METRICS_MEDIA_PERIOD_CRON     = "@every 60s"
	WORKER_CURRENCY_FIAT_PERIOD_CRON     = "@every 6h"
	WORKER_CURRENCY_CRYPTO_PERIOD_CRON   = "@every 1h"
)
